# ==================
# My personal starship prompt config
#
# To learn more about this prompt
# go to https://starship.rs
# ==================


# Print a new line at the start of the prompt 
add_newline = false


# Format/style of the prompt
# def format
# format = """
# $username$hostname$shlvl$kubernetes$directory$git_branch$git_commit$git_state$git_status$hg_branch$docker_context$package$cmake$dart$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$nim$nodejs$ocaml$perl$php$purescript$python$ruby$rust$scala$swift$terraform$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$lua$jobs$battery$time$shell
# $cmd_duration$status$character
# """

# Old custom format
# format = """
# $username$hostname
# $shlvl$kubernetes$directory$git_branch$git_commit$git_state$git_status$hg_branch$docker_context$package$cmake$dart$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$nim$nodejs$ocaml$perl$php$purescript$python$ruby$rust$scala$swift$terraform$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$lua$jobs$battery$shell
# $cmd_duration$status$time$character
# """

format = """
$username$hostname
$directory$git_branch$git_commit$git_state$git_status$hg_branch$package$cmake$dart$java$kotlin$nodejs$php$purescript$python$ruby$rust$scala$swift$terraform$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$lua$jobs$battery$shell
$cmd_duration$status$time$character
"""

# ====== Directory module ======
[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = " "
read_only_style = "bold yellow"
style = "blue bold"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = '…/'


# ====== git modules ======
[git_status]
# This settings look like:
# on  master !(3)?(5)	

staged = '[+\([$count](green)\)](bold green)' 
stashed = '[\$\([$count](red)\)](bold red)'
untracked = '[?\([$count](blue)\)](bold blue)'
modified = '[!\([$count](yellow)\)](bold yellow)'
deleted = '[\([$count](red)\)](bold red)'
ahead = '[⇡\([$count](yellow)\)](bold yellow)'
behind = '[⇣\([$count](red)\)](bold red)'
diverged = '[⇕\([DIV](red)\)](bold red)'
renamed = '[»\([$count](white)\)](bold white)'
conflicted = '[≠\([$count](red)\)](bold red)'
format = '([$all_status$ahead_behind]($style) )'
style = "bold bright-red"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "
only_detached = true

[git_branch]
#symbol = ""
symbol = ""
format = "on [$symbol $branch]($style) "
style = "bold"

# ====== exec time of a command module======
[cmd_duration]
min_time = 1000
format = "took [$duration ](yellow)"

# ====== exit status of previous command module ======
[status]
style = "red bold"
#style = "bg:red bold white"
symbol = "" #
sigint_symbol = "" #
not_found_symbol = "" #
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false


# ====== prompt character ======
# Replace the "❯" symbol in the prompt with "➜" \\$
[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[\\$](bold purple)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
#error_symbol = "[\\$](bold red)" #✗

# success_symbol = "[\\$](bold)"
# error_symbol = "[\\$](bold red)" #✗
success_symbol = "[❯](bold)"
error_symbol = "[❯](bold red)" #✗

# ====== current time module ======
[time]
disabled = true
style = "blue"
format = '[$time]($style) '
time_format = "%H:%M:%S"
use_12hr = false

# ====== hostname module ======
[hostname]
ssh_only = true
format = "[$hostname]($style) at "
style = "bold cyan"

[line_break]
disabled = false

[username]
show_always = false
format = "[$user]($style)"
style_user = "bold yellow"
style_root = "bold bright-red"


# ====== langs configs ======
[aws]
symbol = "  "

[kotlin]
symbol = " "
format = 'with [$symbol\([Kotlin]($style)\)]($style)'
style = 'bold purple'

[conda]
symbol = " "

[dart]
symbol = " "

[lua]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "
style = "bold red"
format = "with [$symbol($version) ]($style)"

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "with [$symbol($version )]($style)"

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "







